services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nifty_user_isolated
      POSTGRES_PASSWORD: nifty_pass_789
      POSTGRES_DB: nifty_db_isolated
    ports:
      - "5434:5432"
    volumes:
      - nifty_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nifty.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  nifty_db_data:
